source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.8', '>= 7.0.8.7'

# Use mysql as the database for Active Record
gem 'mysql2', '~> 0.5'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
# gem "rack-cors"

# フェイクデータの作成
gem 'faker'

# ModelにSchema情報を入れる
gem 'annotate'

# エラー画面の変更
gem 'better_errors'
gem 'binding_of_caller'

# View層を改善
gem 'active_decorator'

# JSON形式のレスポンスを整形
gem 'active_model_serializers'

# 認証機能の実装
gem 'devise'

# タイムゾーン情報を提供する（標準gem）
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]

  # デバッグ用の機能
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]

  # biding.pry用
  gem 'pry-byebug'
  gem 'pry-doc'
  gem 'pry-rails'

  # Lint用
  gem 'rubocop-rails'

  # 環境変数用
  gem 'dotenv-rails'

  # 自動テストライブラリ
  gem 'rspec-rails'

  # テスト用ダミーデータ作成
  gem 'factory_bot_rails'
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
